server:
  port: 8000

spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
      classpath: @java.class.path@

# 按需选择IP地址
---
spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
---
spring:
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
        - 10.0
---
spring:
  cloud:
    inetutils:
      use-only-site-local-interfaces: true

eureka:
  client:
    service-url:
       default-zone: http://localhost:8761/eureka/
      # default-zone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
      # default-zone: http://user:password123@localhost:8761/eureka
      # defaultZone: http://user:password123@localhost:8761/eureka/  #注册 中心已经开启认证
    # Eureka 健康检查
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true
    # 指定IP地址
    # ip-address: 127.0.0.1


