server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/
  # Eureka的自我保护
  # server:
    # enable-self-preservation: false


